// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgFvNx3APcTMT99nwB6QI_G0qiL0D4KGA',
    appId: '1:71649895703:android:cb293789db34289618c352',
    messagingSenderId: '71649895703',
    projectId: 'hasad-3db1d',
    storageBucket: 'hasad-3db1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsZmtPGA7pGLl3QuB-0xc-oAhbH4nCJ_4',
    appId: '1:71649895703:ios:3edb3445077c86b318c352',
    messagingSenderId: '71649895703',
    projectId: 'hasad-3db1d',
    storageBucket: 'hasad-3db1d.firebasestorage.app',
    iosBundleId: 'com.example.hasadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdew3gQbBojKKk6Nuu1rES5BDUlnRQXq0',
    appId: '1:71649895703:web:b2f78773b39c6aea18c352',
    messagingSenderId: '71649895703',
    projectId: 'hasad-3db1d',
    authDomain: 'hasad-3db1d.firebaseapp.com',
    storageBucket: 'hasad-3db1d.firebasestorage.app',
    measurementId: 'G-BMEKMZ5KDN',
  );
}
